In [2]:
import pandas as pd
import numpy as np

In [5]:
def Ret_Pregunta06(m1, m2, m3):
    '''
    Esta función recibe tres array de Numpy de 2 dimensiones cada uno, y devuelve el valor booleano
    True si es posible realizar una multiplicación entre las tres matrices (n1 x n2 x n3),
    y el valor booleano False si no lo es
    Ej:
        n1 = np.array([[0,0,0],[1,1,1],[2,2,2]])
        n2 = np.array([[3,3],[4,4],[5,5]])
        n3 = np.array([1,1],[2,2])
        print(Ret_Pregunta06(n1,n2,n3))
            True            -> Valor devuelto por la función en este ejemplo
        print(Ret_Pregunta06(n2,n1,n3))
            False            -> Valor devuelto por la función en este ejemplo
    '''
    #Tu código aca:

In [7]:
def Ret_Pregunta06(m1, m2, m3):
    '''
    Esta función recibe tres array de Numpy de 2 dimensiones cada uno, y devuelve el valor booleano
    True si es posible realizar una multiplicación entre las tres matrices (n1 x n2 x n3),
    y el valor booleano False si no lo es
    Ej:
        n1 = np.array([[0,0,0],[1,1,1],[2,2,2]])
        n2 = np.array([[3,3],[4,4],[5,5]])
        n3 = np.array([1,1],[2,2])
        print(Ret_Pregunta06(n1,n2,n3))
            True            -> Valor devuelto por la función en este ejemplo
        print(Ret_Pregunta06(n2,n1,n3))
            False            -> Valor devuelto por la función en este ejemplo
    '''
    #Tu código aca:
    try:
        # Intentamos multiplicar las matrices
        result = np.dot(np.dot(m1, m2), m3)
        return True
    except ValueError:
        # Si hay un error al multiplicar, devolvemos False
        return False

# Ejemplo de uso:
n1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
n2 = np.array([[3, 3], [4, 4], [5, 5]])
n3 = np.array([[1, 1], [2, 2]])

print(Ret_Pregunta06(n1, n2, n3))  # Devuelve True
print(Ret_Pregunta06(n2, n1, n3))  # Devuelve False

True
False


## FORMA 2


In [8]:
n1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
n2 = np.array([[3, 3], [4, 4], [5, 5]])
n3 = np.array([[1, 1], [2, 2]])
print(f'[{n1}]\n')
print(f'[{n2}]\n')
print(f'[{n3}]\n')

[[[0 0 0]
 [1 1 1]
 [2 2 2]]]

[[[3 3]
 [4 4]
 [5 5]]]

[[[1 1]
 [2 2]]]



In [14]:
def Ret_Pregunta06(m1, m2, m3): 
    '''
    Esta función recibe tres array de Numpy de 2 dimensiones cada uno, y devuelve el valor booleano
    True si es posible realizar una multiplicación entre las tres matrices (n1 x n2 x n3),
    y el valor booleano False si no lo es
    Ej:
        n1 = np.array([[0,0,0],[1,1,1],[2,2,2]])
        n2 = np.array([[3,3],[4,4],[5,5]])
        n3 = np.array([1,1],[2,2])
        print(Ret_Pregunta06(n1,n2,n3))
            True            -> Valor devuelto por la función en este ejemplo
        print(Ret_Pregunta06(n2,n1,n3))
            False            -> Valor devuelto por la función en este ejemplo
    '''
    #Tu código aca:
    
    if m1.shape[1]!= m2.shape[0]:
        return False
    if m2.shape[1]!= m3.shape[0]:
        return False
    return True